- 👋 Hi, I’m @SAM-29122000
- 👀 I’m interested in coding..
- 🌱 I’m currently learning Gen_AI...
- 💞️ I’m looking to collaborate on Latest Projects...
- 📫 How to reach me Github...
- 😄 Pronouns: SaM...
- ⚡ Fun fact: I love Sukha Puri not Masala puri...

<!---
SAM-29122000/SAM-29122000 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
